version: "2"
volumes:
    log:
    web:
    mongo-data:
services:
  mongo:
    restart: always
    image: mongo:3.0
    volumes:
      - mongo-data:/data/db
  frontend:
    restart: always
    image: briceburg/apache
    ports:
      - "5000:80"
    volumes:
      - web:/usr/local/apache2/htdocs/
  gazouilleur:
    restart: always
    image: scpomedialab/gazouilleur:latest
    build: .
    links:
     - "mongo:mongo"
     - "frontend:frontend"
    env_file:
     - docker-config.env
    volumes:
      - log:/app/log
      - web:/app/web
